version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      # - ./app:/app/
      - ./themes:/app/wp-content/themes
    environment:
      DB_NAME: d0235515
      DB_PASS: root
      DB_PREFIX: hc0vE_
      PLUGINS: >-
        breadcrumb-navxt,
        wp-migrate-db
  db:
    image: mysql:5.7 # or mariadb:10
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
